In [142]:
a = np.arange(36)
a.shape = (6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [144]:
a[0:4,0:4]

array([[ 0,  1,  2,  3],
       [ 6,  7,  8,  9],
       [12, 13, 14, 15],
       [18, 19, 20, 21]])

In [145]:
a[0:6,0:6]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [148]:
import tensorflow as tf

x = tf.range(36)
x = tf.reshape(x, (1,6,6,1))
l = tf.Variable([[0,0,6,6],[0,0,4,4]])
def fn(roi):
    w_stride = (roi[2] - roi[0]) // 2
    h_stride = (roi[3] - roi[1]) // 2    
    roi_pool = []
    for i in range(2):
        h_start = roi[1] + i * h_stride
        for j in range(2):
            w_start = roi[0] + j * w_stride
            val = tf.reduce_max(x[0, h_start:h_start+h_stride, w_start:w_start+w_stride, :])
            roi_pool.append(val)
    roi_pool = tf.reshape(tf.stack(roi_pool,axis=0), (2,2))
    return roi_pool
c = tf.map_fn(fn, l)
c

<tf.Tensor 'map_31/TensorArrayStack/TensorArrayGatherV3:0' shape=(2, 2, 2) dtype=int32>

In [149]:
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    sess.run(c)
    print(c.eval())

[[[14 17]
  [32 35]]

 [[ 7  9]
  [19 21]]]


In [161]:
import tensorflow as tf

a = tf.range(36, dtype=tf.int32)
a = tf.reshape(a, (1,6,6,1))
b = tf.Variable([[0,0,6,6],[0,0,4,4]], dtype=tf.int32)
def fn(roi):
    roi_pool = tf.image.resize_images(a[0, roi[1]:roi[3], roi[0]:roi[2],:], [2,2])
    return roi_pool
c = tf.map_fn(fn, b)
c

<tf.Tensor 'map_38/TensorArrayStack/TensorArrayGatherV3:0' shape=(2, 2, 2, 1) dtype=int32>

In [180]:
c = tf.image.resize(x, [2,2])

with tf.Session() as sess:
    tf.global_variables_initializer().run()
    sess.run(c)
    print(c.eval()[0,:,:,0])

[[ 0.  3.]
 [18. 21.]]
